### ISSUE TITLE
Expected format for Token parameter in AdlsClient.CreateClient(string, string)

### ISSUE THREAD

**Issue by Blackbaud-CameronBlack** [Azure/azure-data-lake-store-net#10]
I am trying to connect to ADLS via a function using MSI.

I see that there is an overloaded method **AdlsClient.CreateClient(string, string)** where the 2nd string is a token, where the format is supposed to be 
"**token** String **Full authorization Token e.g. Bearing: abcddsfere**....."
Is that a typo for **Bearer:** ?

Either way, I can't seem to get the right combination for this to work in a function via MSI authentication:

```
var azureServiceTokenProvider = new AzureServiceTokenProvider();
var accessToken = await azureServiceTokenProvider.GetAccessTokenAsync("https://datalake.azure.net/");
var lakeClient = AdlsClient.CreateClient("<your-data-lake>.azuredatalakestore.net", $"Bearer: {accessToken}");
var access = lakeClient.CheckAccess("/path-to-check/", "--x");
```
Any pointers?

**Comment by rahuldutta90** [comment]
Yes that is typo in my documentation. Will correct it in next release. Can you try this: CreateClient(clientAccountPath, "Bearer " + AccessToken)

Let me know if it works.

**Comment by Blackbaud-CameronBlack** [comment]
Yes, that works, thanks!  I don't know why I had the colon in there...
