### ISSUE TITLE
Recursive ACL application of Defaults should ignore Files

### ISSUE THREAD

**Issue by AlexKeySmith** [Azure/azure-data-lake-store-net#13]
As discovered via the powershell wrapper: https://github.com/Azure/azure-powershell/issues/6171#issuecomment-395488032

It would be helpful when setting default ACLs when applying ACL's recursively that Files are ignored, as it causes problems when needing to apply a new default to folders than already contain files.

I suspect around here: https://github.com/Azure/azure-powershell/blob/7fd657a2e53f7b4f1571acb75bdee2a376c3094d/src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneModels/DataLakeStoreItemAce.cs#L70

That if it's a default it doesn't get added to the changes and therefore results in a Acl Specification List is empty error.

**Comment by rahuldutta90** [comment]
Fixed in the latest release.
