### ISSUE TITLE
Can't copy large file Error "Operation:  failed with  Error: Offset of file is negative."

### ISSUE THREAD

**Issue by nicolasbailly1** [Azure/azure-data-lake-store-net#14]
It happens when files are bigger than 2Gb and it happens when using WriteAsync or CopyAsync methods.
When using Write and Copy methods it works well.

It happens because the integer limit is exceeded. Here is the stack trace :

 Microsoft.Azure.DataLake.Store.AdlsException: Error in appending for file <fileName> at offset 2147483648.
Operation:  failed with  Error: Offset of file is negative.
Last encountered exception thrown after 1 tries. 
[ServerRequestId:]
at Microsoft.Azure.DataLake.Store.AdlsOutputStream.<WriteServiceAsync>d__53.MoveNext()

**Comment by rahuldutta90** [comment]
Acknowledge this. Will fix it in the next release.

**Comment by rahuldutta90** [comment]
Fixed in the latest release.
