### ISSUE TITLE
Unable to control retry logic on AdlsClient.EnumerateDirectory

### ISSUE THREAD

**Issue by maknud** [Azure/azure-data-lake-store-net#15]
It doesn't appear that there is any way to control the retry behavior in AdlsClient.EnumerateDirectory(or any of the methods from what I can tell).

Example:
  AdlsClient client = AdlsClient.CreateClient($"invalidAccount.azuredatalakestore.net", this.Credentials);
  DirectoryEntry entry = client.EnumerateDirectory("/").First();

This takes 30 seconds to fail. It would be nice if this allowed you to declare the retry policy so that you could have this fail immediately if you wanted.

**Comment by rahuldutta90** [comment]
Please use the ListStatus in Core.cs. This gives you more flexibility in how you want to use it. Here is the doc:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.datalake.store.core.liststatusasync?view=azure-dotnet#Microsoft_Azure_DataLake_Store_Core_ListStatusAsync_System_String_System_String_System_String_System_Int32_System_Nullable_Microsoft_Azure_DataLake_Store_UserGroupRepresentation__Microsoft_Azure_DataLake_Store_AdlsClient_Microsoft_Azure_DataLake_Store_RequestOptions_Microsoft_Azure_DataLake_Store_OperationResponse_System_Threading_CancellationToken_
