### ISSUE TITLE
socket exception using ConcurrentAppendAsync

### ISSUE THREAD

**Issue by lpunderscore** [Azure/azure-data-lake-store-net#18]
I have a simple azure function on the changefeed of a cosmos db which "exports" to a datalake. The db has thousands of updates every second so the datalake is structured in such a way to have multiple cosmos "entities" into 1 datalake file (partitioned by minute per entity type).  this is done to follow best practices of not created too many small files in the lake.

The function generates thousands of errors everyday:

Error in concurrent append for file edited-out/entity-type-edited-out/y=2018/m=8/d=6/h=16/m=13/data.json. Operation: CONCURRENTAPPEND failed with Unknown Error: Only one usage of each socket address (protocol/network address/port) is normally permitted Only one usage of each socket address (protocol/network address/port) is normally permitted Source: System.Net.Requests StackTrace: at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
 at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
 at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
 --- End of stack trace from previous location where exception was thrown ---
 at Microsoft.Azure.DataLake.Store.WebTransport.MakeSingleCallAsync(String opCode, String path, ByteBuffer requestData, ByteBuffer responseData, QueryParams qp, AdlsClient client, RequestOptions req, OperationResponse resp, CancellationToken cancelToken, IDictionary`2 customHeaders). Last encountered exception thrown after 1 tries. [Only one usage of each socket address (protocol/network address/port) is normally permitted Only one usage of each socket address (protocol/network address/port) is normally permitted] [ServerRequestId:]

**Comment by rahuldutta90** [comment]
@lpunderscore Have you increased "ServicePointManager.DefaultConnectionLimit"? Our SDK uses HttpWebRequest to send requests. HttpWebRequest uses one connection group for one host (account url). Now parallel connections in a group is controlled by this limit (DefaultConnectionLimit). Maybe you want to try increasing this to 500. LEt me know if it works, else I have to open an issue with dotnet team.

**Comment by lpunderscore** [comment]
@rahuldutta90  will try and see if it fixes the issue.

**Comment by lpunderscore** [comment]
So far I have not received this error in the last 12 hours of running (couple million requests to DL).
Thanks!

Will update if it happens again.

**Comment by rahuldutta90** [comment]
Thanks for the update. I will keep this open for one more day, since this is the first time I saw this error. If there are no more updates, i will close it tomorrow.

**Comment by rahuldutta90** [comment]
Closing the issue since i have not heard about the issue. Please reactivate it if it occurs again.

**Comment by lpunderscore** [comment]
This is happening a lot again now.

This is a simple azure V2 function running on change feed to take json and write to ConcurrentAppendAsync().

I had to stop the function because i'm getting 200 errors per second while running.  

I have set ServicePointManager.DefaultConnectionLimit = 5000; still getting errors.

It's frustrating because using the change feed for this sort of thing is documented and should be straight forward to implement.

Is there something particular with the DL sdk I'm not using correctly?

**Comment by rahuldutta90** [comment]
@lpunderscore are you still facing errors?

**Comment by manums** [comment]
We are facing same issue from our container app running on .NET core. I don't know whether it is relevant, but I have set DefaultConnectionLimit. This has started happening from a week or so. It is not even intermittent. We try write to different files using same ADLSClient instance in parallel.

`await Connection.ADLSClient
                        .ConcurrentAppendAsync(filePath, true, textByteArray, 0, textByteArray.Length)
                        .ConfigureAwait(false)`

It is not that every calls fails but more than some 30% calls are failing due to below exception. I even updated  **Microsoft.Azure.DataLake.Store** to 1.1.11 version.

Exception and stack:

```
Failed to push data to sink with exception Microsoft.Azure.DataLake.Store.AdlsException: 
Error in concurrent append for file **filename**.

Operation: CONCURRENTAPPEND failed with   Unknown Error: 
Only one usage of each socket address (protocol/network address/port) is normally permitted Only one usage of each socket address (protocol/network address/port) is normally permitted 
Source: System.Net.Requests StackTrace:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---

at Microsoft.Azure.DataLake.Store.WebTransport.MakeSingleCallAsync(String opCode, String path, ByteBuffer requestData, ByteBuffer responseData, QueryParams qp, AdlsClient client, RequestOptions req, OperationResponse resp, CancellationToken cancelToken, IDictionary`2 customHeaders).
Last encountered exception thrown after 1 tries. [Only one usage of each socket address (protocol/network address/port) is normally permitted Only one usage of each socket address (protocol/network address/port) is normally permitted]
[ServerRequestId:]
 at Microsoft.Azure.DataLake.Store.AdlsClient.ConcurrentAppendAsync(String path, Boolean autoCreate, Byte[] dataBytes, Int32 offset, Int32 length, CancellationToken cancelToken)

```

**Comment by lpunderscore** [comment]
Leaving this here for documentation purposes.

I am no longer seeing this error  (or any other exception) in my logs using version 1.1.11 in a dotnet core 2.1 azure function connected to cosmos db changefeed. 

Not sure what changed, since we did not change any code on our side.
