### ISSUE TITLE
File properties non-recursive and to memory (not file) 

### ISSUE THREAD

**Issue by igor-betin** [Azure/azure-data-lake-store-net#21]
Why is there even a method to write file properties to a file? Who needs them in another file?
I want last access time and size in a simplest way possible - how do I do it? 

Something like GetFileProperties but async and returning a simple structure.

**Comment by rahuldutta90** [comment]
There are two apis GetDirectoryEntry and GetFileProperties. GetDirectoryEntry is probably what you are looking for. GetDirectoryEntry returns the filestatus containing stream length,accesstime, etc for a given path. GetFileProperties returns the filestatus and/or AclStatus for all the contents (sub directories, files) recursively under a given path. That is why it is necessary to write them in a file. Sorry for confusing names.
