### ISSUE TITLE
MockAdlsClient.CreateFile method fails when overwriting

### ISSUE THREAD

**Issue by dniswonger** [Azure/azure-data-lake-store-net#27]
An attempt to call MockAdlsClient.CreateFile with a duplicate file name and IfExists = Overwrite causes the underlying dictionary to throw 'An item with the same key has already been added' exception.

**Comment by rahuldutta90** [comment]
Ack, will fix it in next release. However one thing to remember is the implementation of MockClient is best-effort only. It wont be fair to expect same behavior from MockClient as AdlsClient

**Comment by rahuldutta90** [comment]
Fixed it.
