### ISSUE TITLE
Support for gen2

### ISSUE THREAD

**Issue by lpunderscore** [Azure/azure-data-lake-store-net#29]
Will support for gen2 be included in this sdk?
Is there an sdk available for gen2?

Thanks

**Comment by yevhen** [comment]
@seguler any hints on sdk release timeframe? thanks!

**Comment by don4of4** [comment]
@seguler Is there any documentation on the REST API?  James said he would publish a link, but I don't see it.  This is important for any real enterprise deployment of this product.

**Comment by lpunderscore** [comment]
I used this article and was able to upload files to dl gen2 account. It's not super straight forward, but it works.

[](https://docs.microsoft.com/en-us/rest/api/storageservices/data-lake-storage-gen2)

**Comment by don4of4** [comment]
@lpunderscore I don't see an endpoint to actually create a file.  Are you saying we can create files with `PUT http://{accountName}.{dnsSuffix}/{filesystem}?resource=filesystem`?  I thought that was to create an account.

**Comment by rahuldutta90** [comment]
Closing this since the current rest api method worked.

**Comment by imeya** [comment]
@lpunderscore , Hello, can you please provide some sample code for the api usage? I tried, but always fail(Even click on the try it button on the page). Thank you.
