### ISSUE TITLE
Need a way to get file info such as ModificationTime 

### ISSUE THREAD

**Issue by hankbeasley** [Azure/azure-data-lake-store-net#3]

**Comment by Vivihung** [comment]
Have you tried these two APIs? 
[AdlsClient.GetDirectoryEntryAsync(String, UserGroupRepresentation, CancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.datalake.store.adlsclient.getdirectoryentryasync?view=azure-dotnet#Microsoft_Azure_DataLake_Store_AdlsClient_GetDirectoryEntryAsync_System_String_Microsoft_Azure_DataLake_Store_UserGroupRepresentation_System_Threading_CancellationToken_)
[AdlsClient.GetDirectoryEntry(String, UserGroupRepresentation, CancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.datalake.store.adlsclient.getdirectoryentry?view=azure-dotnet#Microsoft_Azure_DataLake_Store_AdlsClient_GetDirectoryEntry_System_String_Microsoft_Azure_DataLake_Store_UserGroupRepresentation_System_Threading_CancellationToken_)

They work for both files and directories. 
And the returned [DirectoryEntry](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.datalake.store.directoryentry?view=azure-dotnet) has a property called "**LastModifiedTime**"

**Comment by rahuldutta90** [comment]
Thanks @Vivihung. Yes [AdlsClient.GetDirectoryEntryAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.datalake.store.adlsclient.getdirectoryentryasync?view=azure-dotnet#Microsoft_Azure_DataLake_Store_AdlsClient_GetDirectoryEntryAsync_System_String_Microsoft_Azure_DataLake_Store_UserGroupRepresentation_System_Threading_CancellationToken_) will meet your needs.
