### ISSUE TITLE
Compression (Gzip) support in file upload

### ISSUE THREAD

**Issue by pherbel** [Azure/azure-data-lake-store-net#30]
This sdk would be more useful if it it could support the Gzip compression.

**Comment by sachinsbigdata** [comment]
Hi pherbel,

Thank you for your feedback. We will put into the backlog for ADLS Gen1. Adding @seguler so that he can add it as part of the ADLS Gen2 SDK backlog.

Cheers,
Sachin.

**Comment by rahuldutta90** [comment]
Since we will be adding this in the adlsgen2 backlog, closing the issue here.
