### ISSUE TITLE
Directory watch and delete support

### ISSUE THREAD

**Issue by pherbel** [Azure/azure-data-lake-store-net#31]
In our case we would like to watch a local directory and upload the files to a Data Lake Storage.
After an upload the file can be deleted.
Would be great a fist class sdk support for that case. I think it is very common use case.

**Comment by sachinsbigdata** [comment]
Hi pherbel,

Thank you for your feedback. We will put it into our backlog. Adding @seguler  so that it can be considered for the ADLS Gen2 related SDK.

Cheers.

**Comment by rahuldutta90** [comment]
Since we will be adding this in the adlsgen2 backlog, closing the issue here.
