### ISSUE TITLE
AdlsClient.BulkUpload(...) does not report progress correctly

### ISSUE THREAD

**Issue by sanshan20** [Azure/azure-data-lake-store-net#32]
The AdlsClient.BulkUpload(...) method does not report progress correctly for files.  When a single file is being uploaded, the TransferStatus object  does not have updated values for ChunksTransfered, SizeTransfered, and TotalChunksToTransfer fields.

Progress works well when a folder is uploaded.

**Comment by rahuldutta90** [comment]
@sanshan20 can you please elaborate on your input? What are the sizes of the files? Are you uploading just one file or multiple files?

**Comment by rahuldutta90** [comment]
@sanshan20 We only update the status after upload of one chunk. While that chunk is being uploaded there wont be change in status.

**Comment by sanshan20** [comment]
> @sanshan20 can you please elaborate on your input? What are the sizes of the files? Are you uploading just one file or multiple files?

@rahuldutta90 - I'm uploading one 178 MB file.  The ChunksTransfered fields remains zero.  Never gets updated with the number of chunks uploaded.  And, neither does the SizeTransfered field get updated.

**Comment by rahuldutta90** [comment]
@sanshan20 in that case it is expected, because in this case 1 file is basically a chunk. By the time that file is done uploaded, your upload process ends. And as I mentioned above our granularity level to update the status is once a chunk (240MB) is uploade.
