### ISSUE TITLE
AdlsClient.BulkDownload method returns with 'Access to path is denied' error

### ISSUE THREAD

**Issue by sanshan20** [Azure/azure-data-lake-store-net#39]
AdlsClient.BulkDownload() method always returns with 'Access to path is denied' error, even when trying to save to the Users folder. I'm on Windows 10.  I'm able to create a file with the FileStream class in the same application.

**Comment by pjurri** [comment]
I have the same issue:( can login/connect, EnumerateDirectory, create new folder, but when bulk down or upload i get the same messages. The issue is the local windows 10 path? How did you resolve this issue?

**Comment by sanshan20** [comment]
Hi,
This issue is with the documentation. The description for parameter 'destPath' says "Local destination path. **It should always be a directory**.", which is incorrect.  For files you have to append the file name to the destination path. That fixed the issue for me.

Hope this helps.

**Comment by sanshan20** [comment]
> I have the same issue:( can login/connect, EnumerateDirectory, create new folder, but when bulk down or upload i get the same messages. The issue is the local windows 10 path? How did you resolve this issue?

Hi,
This issue is with the documentation. The description for parameter 'destPath' says "Local destination path. It should always be a directory.", which is incorrect. For files you have to append the file name to the destination path. That fixed the issue for me.

Hope this helps.

**Comment by sanshan20** [comment]
> I have the same issue:( can login/connect, EnumerateDirectory, create new folder, but when bulk down or upload i get the same messages. The issue is the local windows 10 path? How did you resolve this issue?

Hi,
This issue is with the documentation. The description for parameter _destPath_ says "Local destination path. **It should always be a directory**.", which is incorrect. For files you have to append the file name to the destination path. That fixed the issue for me.

Hope this helps.
