### ISSUE TITLE
Support for netcoreapp2.0

### ISSUE THREAD

**Issue by mattdot** [Azure/azure-data-lake-store-net#4]
Package 'Microsoft.Azure.DataLake.Store' is compatible with a subset of the specified frameworks in project

**Comment by rahuldutta90** [comment]
Currently having support to .net452 is a necessity. When we can target our SDK to 4.6.1 then we can target to netcoreapp2.0. (https://docs.microsoft.com/en-us/dotnet/core/tutorials/libraries)
