### ISSUE TITLE
What is the difference between azure.storage.files.datalake and  Microsoft.Azure.DataLake.Store 

### ISSUE THREAD

**Issue by siva-sankaran** [Azure/azure-data-lake-store-net#55]
For newer projects, can we use this( Microsoft.Azure.DataLake.Store ) package to connect with Azure Data Lake Storage ?  Actually I am using azure.storage.files.datalake  nuget package. But there is a scenario to download multiple files . Through internet search I have come to know about BulkDownload() method.  Is it ok to use Microsoft.Azure.DataLake.Store package ? It is neither deprecated nor updated in recent days.  Can I use both this package in the same project ? 

More Over samples repo (https://github.com/Azure-Samples/data-lake-store-adls-dot-net-samples) provided in readme file  is changed to azure.storage.files.datalake library. Can we get some explicit differences between these libraries ?

**Comment by EverettSummer** [comment]
This SDK is for ADLSGen1, the Azure.Storage.Files.DataLake is for ADLSGen2
