### ISSUE TITLE
AdlsClient.CreateClient throws ArgumentException when my account FQDN contains "-"

### ISSUE THREAD

**Issue by Vivihung** [Azure/azure-data-lake-store-net#6]
I'm trying to access our ADLS with AAD token via ADLS SDK,
However, this line in my code got exception from the SDK.
```C#
AdlsClient.CreateClient(clientAccountName, clientCreds2);
```

Error
>Unhandled Exception: System.ArgumentException: Account name test-ppe-c14.azuredatalakestore.net is invalid. Specify the full account including the domain name.
   at Microsoft.Azure.DataLake.Store.AdlsClient..ctor(String accnt, Int64 clientId, ServiceClientCredentials creds, Boolean skipAccntValidation)
   at Microsoft.Azure.DataLake.Store.AdlsClient.CreateClient(String accountFqdn, ServiceClientCredentials creds)
   at AdlsSdkSamples.Program.Main(String[] args) in e:\GitHub\data-lake-store-adls-dot-net-samples\AdlsSdkSamples\Program.cs:line 40

By looking at the SDK source code, I believe it is the following regex which determines my ADLS FQDN is invalid.

```C#
        private bool IsValidAccount(string accnt)
        {
            return Regex.IsMatch(accnt, @"^[a-zA-Z0-9]+\.[a-zA-Z0-9\-][a-zA-Z0-9.\-]*$");
        }
```

But, I think my ADLS FQDN is a **valid** one in Azure portal (or I cannot create it, right?)
Here is my ADLS FQDN pattern
**test-ppe-c14.azuredatalakestore.net**

Looks like a bug in the SDK to me.

Edit note [1/9/2018 Updated]:
After chat with the team, Azure portal doesn't allow '-' in the account name.
It's our team worked with Azure to create those ADLS account which might bypass the Azure portal's validation. Therefore, this issue is a special case.

**Comment by rahuldutta90** [comment]
Acknowledge it. Will relax the validity check for account names. Will roll out the change in the next release (probably next week).

**Comment by rahuldutta90** [comment]
Fixed and released 1.0.5

**Comment by vit100** [comment]
Not sure if my issue related to this fix or I do something wrong, but 
this regex fails for my FQDN = https://dataingestpocadls2produc.dfs.core.windows.net/

Should it be changed or I use wrong address?

**Comment by rahuldutta90** [comment]
FQDN would be "dataingestpocadls2produc.dfs.core.windows.net".
