### ISSUE TITLE
Inline documentation: Many functions do not include thread safety information. 

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-data-lake-store-net#9]
This is a reference doc issue that requires a change to the underlying `///` comments.

From @leftler (https://github.com/Azure/azure-docs-sdk-dotnet/issues/364):

> Many class definitions do not include thread safety information. For example for https://github.com/Azure/azure-docs-sdk-dotnet/blob/b39513f/xml/Microsoft.Azure.DataLake.Store/AdlsClient.xml does not mention anywhere if the class's methods are safe to use from multiple threads (like WebClient is) or if we need a instance per thread.

cc: @nitinme

**Comment by rahuldutta90** [comment]
Acknowledge. Will try to fix it in next release.

**Comment by CamSoper** [comment]
Thank you!

**Comment by rahuldutta90** [comment]
Resolved in the new release.
